# Generated by Django 4.2.2 on 2023-06-12 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_alter_category_id_alter_product_id_alter_review_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.custumer')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='ISBN',
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='Edition',
            field=models.IntegerField(default=1212),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Format',
            field=models.CharField(choices=[('ورقي', 'ورقي'), ('الكتروني', 'الكتروني')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Language',
            field=models.CharField(choices=[('عربي', 'عربي'), ('انكليزي', 'انكليزي')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Page_Count',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Series',
            field=models.IntegerField(default=212),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Target_audience',
            field=models.CharField(choices=[('مبرمجين', 'مبرمجين'), ('عامة الناس', 'عامة الناس'), ('اقتصاديين', 'اقتصاديين'), ('أطفال', 'أطفال')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.DateField(default='2023-06-12'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem1',
            fields=[
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookshop.order1')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items1', to='bookshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='BookF',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('fatoris', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=True)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.custumer')),
            ],
        ),
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
