# Generated by Django 4.2.2 on 2023-06-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0009_bookrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRating',
        ),
    ]
