# Generated by Django 4.2.2 on 2023-06-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0010_delete_bookrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('important', 'مهم'), ('exclude', 'استبعاد'), ('neutral', 'بدون تمييز')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.custumer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
