# Generated by Django 4.2.2 on 2023-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0014_remove_custumer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='name',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
