# Generated by Django 4.2.2 on 2023-07-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0019_alter_bookf_custumer_alter_bookpreference_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Format',
            field=models.CharField(choices=[('ورقي', 'ورقي'), ('الكتروني', 'الكتروني')], default='ورقي', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Language',
            field=models.CharField(choices=[('عربي', 'عربي'), ('انكليزي', 'انكليزي')], default='عربي', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/bookCovers'),
        ),
    ]
